name: iai-assessment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - scikit-learn>=1.0.0
  - pip>=21.0.0
  - pip:
    - openai>=1.0.0
    - pytest>=6.2.5
    - black>=21.5b2
    - flake8>=3.9.2
    - mypy>=0.812
    - themefinder>=0.5.4
